spring:
  application:
    name: ikuncoffee

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ikun_coffee
    username: root
    password: 123456

  sql:
    init:
      mode: always
      platform: mysql

#logging:
#  level:
#    root: debug
#  pattern:
#    console: "%d - %m%n"


server:
  port: 8888

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret: helloworldhelloworldhelloworldhelloworldhelloworldhelloworld
  expiration: 3600000

knife4j:
  enable: true
  setting:
    language: zh_cn